[project]
name = "dance-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.129.0",
    "uvicorn>=0.40.0",
    "yt-dlp>=2026.2.4",
]

[dependency-groups]
dev = [
    "rich>=14.3.2",
]
